models:
  - name: stg_customers_orders
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: order_date
        tests:
          - not_null
      - name: order_amount
        tests:
          - not_null

  